python3 ../../../main_pretrain.py \
    --dataset multi_views_imagenet_with_mask \
    --backbone resnet50_MNCRL \
    --data_dir /data1/1K_New/ \
    --train_dir train \
    --mask_dir train_binary_mask_by_USS \
    --max_epochs 100 \
    --gpus 0,1,2,3,4,5,6,7 \
    --accelerator gpu \
    --strategy ddp \
    --sync_batchnorm \
    --precision 16 \
    --optimizer sgd \
    --lars \
    --eta_lars 0.001 \
    --exclude_bias_n_norm \
    --scheduler warmup_cosine \
    --lr 0.5 \
    --accumulate_grad_batches 1 \
    --classifier_lr 0.2 \
    --weight_decay 1e-6 \
    --batch_size 512 \
    --num_workers 8 \
    --brightness 0.4 0.4 0.4 0.4 \
    --contrast 0.4 \
    --saturation 0.2 \
    --hue 0.1 \
    --gaussian_prob 1.0 \
    --solarization_prob 0.2 \
    --crop_size 224 \
    --rda_num_ops 2 \
    --rda_magnitude 9 \
    --ada_policy imagenet \
    --num_crops_per_aug 1 1 1 1 \
    --name MNCLR_Multi_views-resnet50-imagenet-100ep \
    --entity mlbrl \
    --project solo \
    --wandb \
    --save_checkpoint \
    --method mncrl_edit \
    --mask_weigted_loss 0.5 \
    --weigted_loss 0.5\
    --loss_type mask_loss \
    --mlp_layer 2 \
    --proj_output_dim 512 \
    --proj_hidden_dim 4096 \
    --pred_hidden_dim 4096 \
    --base_tau_momentum 0.99 \
    --final_tau_momentum 1.0 \
    --momentum_classifier \
    --checkpoint_dir /data1/solo_ckpt \
